name: CI tempo
on: push

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
      - name: Verificar ação GitHub
        uses: actions/checkout@v2

      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Rodar testes
        run: |
          python manage.py test