name: cd/di tempo
on: push
jobs:
  test_project:
    runs-on: ubunti-latest
    steps:
      -name: verificar ação guithub
      uses:actions/checkout@v2
      -name: instalar
      run: |
        pip install django
      -name: testar
      run: |
        python manage.py runserver
